"""add paper processing fields

Revision ID: 818932a97462
Revises: fa69938410c8
Create Date: 2026-01-19 12:12:47.195655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818932a97462'
down_revision: Union[str, Sequence[str], None] = 'fa69938410c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('processing_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('papers', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('papers', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('papers', sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_papers_processing_status'), 'papers', ['processing_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_processing_status'), table_name='papers')
    op.drop_column('papers', 'processing_completed_at')
    op.drop_column('papers', 'processing_started_at')
    op.drop_column('papers', 'retry_count')
    op.drop_column('papers', 'processing_error')
    op.drop_column('papers', 'extracted_text')
    op.drop_column('papers', 'processing_status')
    # ### end Alembic commands ###
