"""add supabase_uid to users

Revision ID: db9c11e5334a
Revises: ad1f52da0cb9
Create Date: 2026-01-19 21:09:55.853801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9c11e5334a'
down_revision: Union[str, Sequence[str], None] = 'ad1f52da0cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # 1. Add column as nullable first
    op.add_column('users', sa.Column('supabase_uid', sa.String(length=36), nullable=True))
    
    # 2. Populate existing rows with a unique value (using uuid)
    import uuid
    connection = op.get_bind()
    # Fetch all user ids
    results = connection.execute(sa.text("SELECT id FROM users")).fetchall()
    
    for row in results:
        uid = str(uuid.uuid4())
        connection.execute(
            sa.text("UPDATE users SET supabase_uid = :uid WHERE id = :id"),
            {"uid": uid, "id": row[0]}
        )

    # 3. Alter column to be not null
    op.alter_column('users', 'supabase_uid', nullable=False)

    op.create_index(op.f('ix_users_supabase_uid'), 'users', ['supabase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_supabase_uid'), table_name='users')
    op.drop_column('users', 'supabase_uid')
    op.alter_column('chunks', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
